#!/bin/sh

set -e

repo=$(dirname $0)
cd "$repo/native-host"

if ! which pandoc > /dev/null; then
  echo "Error: \"pandoc\" is not installed"
  exit 1
fi

if ! cargo build --release; then
  echo "Error: Native host failed to compile" 2>&1
  exit 1
fi

bin_dir="$HOME/.local/bin"
bin="$bin_dir/vim-compose-native-host"

manifest_name="com.mbid.vim.compose.json"

escaped_bin="$(echo $bin | sed 's|/|\\/|g')"
manifest_content_gecko="$(cat "$manifest_name.gecko" | sed s/PATH/$escaped_bin/)"
manifest_content_chrome="$(cat "$manifest_name.chrome" | sed s/PATH/$escaped_bin/)"

chromium_config="$HOME/.config/chromium"
google_chrome_config="$HOME/.config/google-chrome"
firefox_config="$HOME/.mozilla"

if ! [ -d "$chromium_config" ] & ! [ -d "$google_chrome_config" ] & ! [ -d "$firefox_config" ]; then
  echo "Error: Could not find google-chrome or chromium profile" 2>&1
  echo "None of \"$chromium_config\", \"$google_chrome_config\" or \"$firefox_config\" exist" 2>&1
  exit 1
fi

mkdir -p "$bin_dir"
echo "Installing native host to $bin_dir"
cp target/release/native-host "$bin"

install_manifest() {
	content="$1"
  dir="$2"
  echo "Installing native host manifest to $dir"
	mkdir -p "$dir"
  echo "$content" > "$dir/$manifest_name"
}

if [ -d "$chromium_config" ]; then
	install_manifest "$manifest_content_chrome" "$chromium_config/NativeMessagingHosts"
fi
if [ -d "$chrome_config" ]; then
	install_manifest "$manifest_content_chrome" "$google_chrome_config/NativeMessagingHosts"
fi
if [ -d "$firefox_config" ]; then
	install_manifest "$manifest_content_gecko" "$firefox_config/native-messaging-hosts"
fi
